tap "acsandmann/tap"
tap "grishka/grishka"
tap "netbirdio/tap"
tap "tudorandrei/muzik"

brew "acsandmann/tap/menuanywhere"

cask "grishka/grishka/neardrop"
cask "netbirdio/tap/netbird-ui"
cask "tudorandrei/muzik/muzik"
